### ISSUE TITLE
Unclear what counts as a Set for unilateral exercises (e.g. dead bug)

### ISSUE THREAD

**Issue by TimMaa** [TimMaa/baked-and-shredded#4]
For unilateral exercises like the dead bug (where each side is worked separately), the app doesn't make it clear what counts as one Set — e.g. is a Set one rep per side, or both sides together? Reported by the user; not yet investigated.

**Comment by TimMaa** [comment]
> *This was generated by AI during triage.*

**Verification:** Confirmed by code and domain inspection — the domain has no concept of "unilateral" anywhere (Exercise/WorkoutExercise have no such field), so there is genuinely nothing telling the user or the AI generator what a Set means for an exercise like dead bug. This was resolved via a grilling session with the maintainer; decisions are now recorded in `CONTEXT.md` (new `Unilateral Exercise` term, sharpened `Set` definition) and `docs/adr/0001-no-per-side-asymmetric-tracking-for-unilateral-exercises.md`.

## Agent Brief

**Category:** bug
**Summary:** Introduce a persisted `Unilateral Exercise` concept so the app (and AI generation/classification) can be clear about what a Set means for exercises worked one side at a time

**Current behavior:**
There is no notion of "unilateral" anywhere in the domain. An Exercise like dead bug, single-arm row, or single-leg deadlift is tracked identically to a bilateral exercise: a flat `sets` count with no indication of whether the target reps/weight apply to one side, both sides combined, or both sides each. Neither the Exercise editor, the live Session view, single-exercise AI Classification, nor AI Workout Generation say anything about sides. Users can't tell what one Set is supposed to mean for these exercises.

**Desired behavior:**
- Exercise gains a persisted `unilateral` boolean property.
- One Set for a Unilateral Exercise means completing the movement on **both** sides once; its target/actual reps and weight are understood as **per side**, not doubled and not split into a separate left/right breakdown. This keeps a Workout's `sets` count meaning the same thing whether or not the exercise is unilateral.
- The Exercise create/edit UI exposes a manual "Unilateral" toggle, independent of AI, so it's always user-correctable — the same way focus areas and equipment already are.
- Single-exercise AI Classification detects and sets `unilateral` for a new exercise, using the same judgment Workout Generation needs.
- AI Workout Generation's exercise-creation path sets `unilateral` on any new exercise it creates, using that same judgment (this is the "Gemini should be more aware" part of the original report).
- Wherever a Set's reps/weight are shown for a Unilateral Exercise (live Session active-set card, Workout editor's exercise list), the copy makes the "per side" convention explicit (e.g. "10 reps / side") instead of leaving it ambiguous, directly addressing the original complaint.
- The existing Bulk Exercise Re-analysis feature (which already re-runs AI classification across the whole library to refresh description/tip/focus areas) is extended to also detect and backfill `unilateral` for existing exercises when the user runs it.
- On the schema migration adding the `unilateral` field, existing Exercise rows default to `false` — there is no automatic backfill outside of running Bulk Re-analysis.

**Key interfaces:**
- `Exercise` type gains `unilateral: boolean`.
- The single-exercise AI Classification result type, the Bulk Re-analysis result type, and the AI Workout Generation new-exercise shape all need to carry `unilateral` alongside the fields they already produce (description, tip, focusAreas, equipment).
- No change to `WorkoutExercise` or `SessionSet` — per ADR 0001, there is no per-side split anywhere in the data model; a Set's actual stays a single reps/weight number.

**Acceptance criteria:**
- [ ] `Exercise` has a persisted `unilateral` field; existing exercises default to `false` after migration.
- [ ] The Exercise editor has a manual toggle for `unilateral`, correctable independent of any AI action.
- [ ] Running single-exercise AI Classification on an inherently one-sided exercise (e.g. "Single-Arm Row") sets `unilateral: true`.
- [ ] Running AI Workout Generation with a prompt that implies unilateral movements creates new exercises with `unilateral` set correctly.
- [ ] Running Bulk Exercise Re-analysis over an existing library updates `unilateral` on exercises that need it, alongside the fields it already refreshes.
- [ ] The live Session view and the Workout editor both clearly indicate "per side" for a Unilateral Exercise's target/actual reps and weight.
- [ ] A Unilateral Exercise's Set still counts as one Set toward the Workout's total (`sets` count is unaffected by the flag).

**Out of scope:**
- Per-side (left/right) actual tracking — explicitly rejected, see `docs/adr/0001-no-per-side-asymmetric-tracking-for-unilateral-exercises.md`.
- Any change to how total volume, timing, or exercise ordering is computed to account for unilateral exercises effectively taking longer to perform.
- Retroactively re-running Bulk Re-analysis automatically — it remains a user-triggered action.

**Comment by TimMaa** [comment]
Fixed: Exercise gains a persisted unilateral flag (AI-detected via classify/generate/reanalyze, or manually toggled), with 'each side counts as this set' surfaced in the workout editor and live session. Backfilled via a DB migration so existing rows default to false. See commits 4e996d4/0dcc644.
